TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.4
  max_rotational_vel: 0.5
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false
  meter_scoring: true
  controller_frequency: 10.0