local_costmap:
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
  inflation_radius: 0.55
  
  observation_sources: laser_scan_sensor
  laser_scan_sensor: 
    #sensor_frame: dtw_robot1/front_laser_link
    #topic: /dtw_robot1/front_laser/scan
    data_type: LaserScan
    marking: true
    clearing: true

  #global_frame: dtw_robot1/odom
  #robot_base_frame: dtw_robot1/base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
