local_costmap:
  #global_frame: dtw_robot1/odom
  #robot_base_frame: dtw_robot1/base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
