sudo: required
cache:
- apt
language: generic

# ros distro
matrix:
  include:
  # - name: "Xenial kinetic"
  #   dist: xenial
  #   env: ROS_DISTRO=kinetic
  - name: "Bionic melodic"
    dist: bionic
    env: ROS_DISTRO=melodic

# env
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

before_install:
  # install ros
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt update
  # ros base
  - sudo apt install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-desktop-full
  # additional apt package for build
  # - sudo apt install -y ros-$ROS_DISTRO-jsk-rviz-plugins
  # - sudo apt install -y ros-$ROS_DISTRO-moveit-ros
  # - sudo apt install -y ros-$ROS_DISTRO-move-base
  # - sudo apt install -y ros-$ROS_DISTRO-json-transport
  # - sudo apt install -y ros-$ROS_DISTRO-ifopt
  # - sudo apt install -y libarmadillo-dev libarmadillo6
  # source & rosdep
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - sudo rosdep init
  - rosdep update

install:
  # make catkin_ws
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .
  # additional src package for build
  # - git clone https://github.com/tysik/obstacle_detector.git

script:
  # build
  - cd ~/catkin_ws/src/ros_lecture
  - git submodule update --init --recursive
  - rosdep install -i --from-paths ./
  - cd ~/catkin_ws
  - catkin_make
