wheel_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : '/wheel_robot/left_wheel_joint'
    right_wheel : '/wheel_robot/right_wheel_joint'
    publish_rate: 20.0               # default: 50
    pose_covariance_diagonal : [1000000.0, 1000000.0, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
    twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 0.5]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.20
    wheel_radius : 0.05

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0
          
    # Base frame_id
    base_frame_id: wheel_robot/base_link #default: base_link
    odom_frame_id: wheel_robot/odom #default: odom
    enable_odom_tf: false
          
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.55  # m/s
        min_velocity           : -0.55 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.5  # m/s^2
        min_acceleration       : -0.2 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0  # rad/s
        min_velocity           : -2.0
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0
