name: ROS build workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: noetic

    - name: Install catkin tool
      run: sudo apt-get install python3-catkin-tools

    - name: Init workspace
      run: |
        source /opt/ros/noetic/setup.bash
        mkdir -p ${CATKIN_WS}/src
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: pre build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}/src/ros_lecture
        git submodule update --init --recursive
        rosdep update
        rosdep install -i -y --from-paths ./

    - name: build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}
        catkin build
        